# Generated by Django 6.0.2 on 2026-02-21 10:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Bunday foydalanuvchi nomi allaqachon mavjud.'}, help_text='Majburiy. 50 tagacha belgi. Faqat harflar va raqamlar.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Foydalanuvchi nomi')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta manzili')),
                ('rol', models.CharField(choices=[('admin', 'Administrator'), ('oqituvchi', 'O‘qituvchi'), ('oquvchi', 'O‘quvchi'), ('ota_ona', 'Ota-ona')], default='oquvchi', max_length=20, verbose_name='Tizimdagi vazifasi')),
                ('telefon', models.CharField(blank=True, help_text='Masalan: +998901234567', max_length=15, null=True, verbose_name='Telefon raqami')),
                ('telegram_id', models.CharField(blank=True, help_text='Xabarnomalar yuborish uchun ishlatiladi.', max_length=20, null=True, verbose_name='Telegram ID')),
                ('farzandi', models.ForeignKey(blank=True, help_text="Faqat ota-ona foydalanuvchisi uchun to'ldiriladi.", limit_choices_to={'rol': 'oquvchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_onasi', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan farzandi (O'quvchi)")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
