# Generated by Django 6.0.2 on 2026-02-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hisoblar', '0001_initial'),
        ('talim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='sinf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinf_oquvchilari', to='talim.sinf', verbose_name='Sinfi'),
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
