# Generated by Django 6.0.2 on 2026-02-14 04:29

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisoblar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foydalanuvchi',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='farzandi',
            field=models.ForeignKey(blank=True, help_text="Faqat ota-ona foydalanuvchilari uchun to'ldiriladi.", limit_choices_to={'rol': 'oquvchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_onasi', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan o'quvchi"),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrator'), ('oqituvchi', 'O‘qituvchi'), ('oquvchi', 'O‘quvchi'), ('ota_ona', 'Ota-ona')], default='oquvchi', max_length=20, verbose_name='Tizimdagi vazifasi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='telefon',
            field=models.CharField(blank=True, help_text='Masalan: +998901234567', max_length=15, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bunday foydalanuvchi nomi allaqachon mavjud.'}, help_text='Majburiy. 150 tagacha belgi. Faqat harflar, raqamlar va @/./+/-/_ belgilari ruxsat etiladi.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Foydalanuvchi nomi'),
        ),
    ]
