# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisoblar', '0002_initial'),
        ('talim', '0002_alter_fan_options_alter_sinf_options_alter_baho_izoh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='farzandi',
            field=models.ForeignKey(blank=True, help_text='Faqat ota-ona foydalanuvchisi uchun farzandini tanlang.', limit_choices_to={'rol': 'oquvchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_onasi', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan farzandi (O'quvchi)"),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrator'), ('oqituvchi', 'O‘qituvchi'), ('oquvchi', 'O‘quvchi'), ('ota_ona', 'Ota-ona')], default='oquvchi', help_text='Foydalanuvchining saytdagi vakolatlarini belgilaydi.', max_length=20, verbose_name='Tizimdagi vazifasi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='sinf',
            field=models.ForeignKey(blank=True, help_text="O'quvchi qaysi sinfda o'qishini belgilang.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinfdagi_oquvchilar', to='talim.sinf', verbose_name='Sinfi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='telefon',
            field=models.CharField(blank=True, help_text='Namuna: +998901234567', max_length=15, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram bot orqali bildirishnomalar yuborish uchun kerak.', max_length=20, null=True, verbose_name='Telegram ID raqami'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bunday foydalanuvchi nomi tizimda allaqachon mavjud. Iltimos, boshqa nom tanlang.'}, help_text='Majburiy. 150 tagacha belgi. Faqat harflar, raqamlar va @/./+/-/_ belgilari ruxsat etiladi.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Foydalanuvchi nomi (Login)'),
        ),
    ]
