# Generated by Django 6.0.2 on 2026-03-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisoblar", "0003_alter_foydalanuvchi_farzandi_and_more"),
    ]

    operations = [
        # IZOH: Bu migratsiya bazadagi ustunlarni o'zgartirmaydi, faqat admin panelda
        # ko'rinadigan nomlar/izohlarni (verbose_name/help_text) o'zbekchalashtiradi.
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Foydalanuvchi faol bo'lsa, tizimdan foydalanishi mumkin. O'chirish o'rniga faolsizlantiring.",
                verbose_name="Faol",
            ),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Belgilansa, foydalanuvchi admin (boshqaruv) paneliga kira oladi.",
                verbose_name="Xodim holati",
            ),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Belgilansa, foydalanuvchi barcha huquqlarga ega bo'ladi (alohida ruxsat berish shart emas).",
                verbose_name="Super-admin holati",
            ),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi kirish"),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Foydalanuvchi biriktirilgan guruhlar ro'yxati.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="Guruhlar",
            ),
        ),
        migrations.AlterField(
            model_name="foydalanuvchi",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ushbu foydalanuvchiga bevosita berilgan huquqlar.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="Foydalanuvchi huquqlari",
            ),
        ),
    ]

