# Generated by Django 6.0.2 on 2026-02-21 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OquvchiTahlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortacha_ball', models.FloatField(default=0.0, verbose_name="O'rtacha ball")),
                ('trend', models.CharField(choices=[('osish', "O'sish dinamikasi (Yaxshi)"), ('pasayish', 'Pasayish dinamikasi (Xavf)'), ('barqaror', 'Barqaror holat')], default='barqaror', max_length=20, verbose_name='Bilim trendi')),
                ('xavf_ostida', models.BooleanField(default=False, help_text="O'rtacha ball 3.5 dan past bo'lsa, tizim ogohlantiradi.", verbose_name='Xavf ostidami?')),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True, verbose_name='Oxirgi tahlil vaqti')),
                ('oquvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tahlil_markazi', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi tahlili",
                'verbose_name_plural': "O'quvchilar tahlillari",
                'db_table': 'oquvchi_tahlillari',
            },
        ),
    ]
