# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahlil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oquvchitahlili',
            options={'ordering': ['ortacha_ball'], 'verbose_name': "O'quvchi tahlili", 'verbose_name_plural': "O'quvchilar tahlillari"},
        ),
        migrations.AlterField(
            model_name='oquvchitahlili',
            name='oquvchi',
            field=models.OneToOneField(limit_choices_to={'rol': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='tahlil_markazi', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='oquvchitahlili',
            name='ortacha_ball',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="O'quvchining barcha fanlar bo'yicha jami o'rtacha natijasi.", max_digits=3, verbose_name="O'rtacha ball"),
        ),
        migrations.AlterField(
            model_name='oquvchitahlili',
            name='trend',
            field=models.CharField(choices=[('osish', '📈 O‘sish dinamikasi (Ijobiy)'), ('pasayish', '📉 Pasayish dinamikasi (Xavf)'), ('barqaror', '➡ Barqaror holat')], default='barqaror', help_text="Oxirgi baholar tahlili asosida bilim o'zgarishi.", max_length=20, verbose_name='Bilim trendi'),
        ),
        migrations.AlterField(
            model_name='oquvchitahlili',
            name='xavf_ostida',
            field=models.BooleanField(default=False, help_text="Agar o'rtacha ball 3.5 dan past bo'lsa, ota-onaga ogohlantirish yuboriladi.", verbose_name='Xavf ostidami?'),
        ),
    ]
