# Generated by Django 6.0.2 on 2026-02-21 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'fanlar',
            },
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True, verbose_name='Sinf nomi')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'db_table': 'sinflar',
            },
        ),
        migrations.CreateModel(
            name='Taqsimot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(choices=[('1', 'Dushanba'), ('2', 'Seshanba'), ('3', 'Chorshanba'), ('4', 'Payshanba'), ('5', 'Juma'), ('6', 'Shanba')], max_length=1, verbose_name='Hafta kuni')),
                ('soat', models.TimeField(verbose_name='Dars vaqti')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.fan')),
                ('oqituvchi', models.ForeignKey(limit_choices_to={'rol': 'oqituvchi'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslari', to='talim.sinf')),
            ],
            options={
                'verbose_name': 'Dars taqsimoti',
                'verbose_name_plural': 'Darslar taqsimoti',
                'db_table': 'dars_taqsimotlari',
                'unique_together': {('sinf', 'kun', 'soat')},
            },
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu_nomi', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('uy_vazifasi', models.TextField(blank=True, null=True, verbose_name='Uyga vazifa')),
                ('sana', models.DateField(verbose_name="Dars o'tilgan sana")),
                ('taqsimot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzulari', to='talim.taqsimot')),
            ],
            options={
                'verbose_name': 'Dars mavzusi',
                'verbose_name_plural': 'Dars mavzulari',
                'db_table': 'dars_mavzulari',
                'unique_together': {('taqsimot', 'sana')},
            },
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keldi', models.BooleanField(default=True, verbose_name='Keldi')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomati', to=settings.AUTH_USER_MODEL)),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat_yozuvi', to='talim.mavzu')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'davomat',
                'unique_together': {('oquvchi', 'mavzu')},
            },
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymati', models.PositiveSmallIntegerField(verbose_name='Baho')),
                ('izoh', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholari', to=settings.AUTH_USER_MODEL)),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholar_ruyxati', to='talim.mavzu')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'db_table': 'baholar',
                'unique_together': {('oquvchi', 'mavzu')},
            },
        ),
    ]
