# Generated by Django 6.0.2 on 2026-02-19 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'fanlar',
            },
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True, verbose_name='Sinf nomi')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'db_table': 'sinflar',
            },
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu_nomi', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('sana', models.DateField(auto_now_add=True, verbose_name="Dars o'tilgan sana")),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.fan', verbose_name='Fan')),
                ('oqituvchi', models.ForeignKey(limit_choices_to={'rol': 'oqituvchi'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.sinf', verbose_name='Sinf')),
            ],
            options={
                'verbose_name': 'Dars mavzusi',
                'verbose_name_plural': 'Dars mavzulari',
                'db_table': 'dars_mavzulari',
                'unique_together': {('sinf', 'fan', 'sana')},
            },
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymati', models.PositiveSmallIntegerField(verbose_name='Baho')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi")),
                ('oquvchi', models.ForeignKey(limit_choices_to={'rol': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='baholari', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholar', to='talim.mavzu', verbose_name='Dars mavzusi')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'db_table': 'baholar',
                'unique_together': {('oquvchi', 'mavzu')},
            },
        ),
    ]
