# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={'ordering': ['nomi'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='sinf',
            options={'ordering': ['nomi'], 'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
        migrations.AlterField(
            model_name='baho',
            name='izoh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'qituvchi fikri"),
        ),
        migrations.AlterField(
            model_name='baho',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baholar_ruyxati', to='talim.mavzu', verbose_name='Dars mavzusi'),
        ),
        migrations.AlterField(
            model_name='baho',
            name='oquvchi',
            field=models.ForeignKey(limit_choices_to={'rol': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='baholari', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='baho',
            name='qiymati',
            field=models.PositiveSmallIntegerField(help_text="1 dan 5 gacha bo'lgan raqam", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho'),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='keldi',
            field=models.BooleanField(default=True, verbose_name='Ishtirok etdi'),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat_yozuvi', to='talim.mavzu', verbose_name='Dars mavzusi'),
        ),
        migrations.AlterField(
            model_name='davomat',
            name='oquvchi',
            field=models.ForeignKey(limit_choices_to={'rol': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='davomati', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='mavzu_nomi',
            field=models.CharField(max_length=255, verbose_name='Dars mavzusi'),
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='taqsimot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzulari', to='talim.taqsimot', verbose_name='Dars jadvali bandi'),
        ),
        migrations.AlterField(
            model_name='sinf',
            name='nomi',
            field=models.CharField(help_text='Masalan: 9-A', max_length=50, unique=True, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='taqsimot',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.fan', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='taqsimot',
            name='oqituvchi',
            field=models.ForeignKey(limit_choices_to={'rol': 'oqituvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='biriktirilgan_darslari', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul o'qituvchi"),
        ),
        migrations.AlterField(
            model_name='taqsimot',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dars_jadvali', to='talim.sinf', verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='taqsimot',
            name='soat',
            field=models.TimeField(verbose_name='Dars boshlanish vaqti'),
        ),
    ]
