# Generated by Django on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talim", "0002_alter_fan_options_alter_sinf_options_alter_baho_izoh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinf",
            name="smena",
            field=models.CharField(
                choices=[("1", "1-smena (08:00-13:00)"), ("2", "2-smena (13:00-17:55)")],
                default="1",
                help_text="Sinf qaysi smenada o'qishini tanlang.",
                max_length=1,
                verbose_name="Smena",
            ),
        ),
    ]

