# Generated by Django 6.0.2 on 2026-02-21 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogohlantirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255, verbose_name='Xabar sarlavhasi')),
                ('matn', models.TextField(verbose_name='Xabar mazmuni')),
                ('turi', models.CharField(choices=[('baho', '📊 Baho haqida'), ('davomat', '🕒 Davomat haqida'), ('intizom', '⚠️ Intizom haqida'), ('umumiy', '📢 Umumiy e’lon')], default='umumiy', max_length=20, verbose_name='Xabar turi')),
                ('oqilgan', models.BooleanField(default=False, verbose_name='O‘qilganmi?')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('kimga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalari', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Ogohlantirish',
                'verbose_name_plural': 'Ogohlantirishlar',
                'db_table': 'ogohlantirishlar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
    ]
