# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xabarlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogohlantirish',
            name='kimga',
            field=models.ForeignKey(help_text="Xabar yuborilishi kerak bo'lgan foydalanuvchini tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalari', to=settings.AUTH_USER_MODEL, verbose_name='Xabarni qabul qiluvchi'),
        ),
        migrations.AlterField(
            model_name='ogohlantirish',
            name='matn',
            field=models.TextField(help_text='Xabarning batafsil mazmuni.', verbose_name="Xabar to'liq matni"),
        ),
        migrations.AlterField(
            model_name='ogohlantirish',
            name='oqilgan',
            field=models.BooleanField(default=False, help_text="Foydalanuvchi xabarni ochib ko'rgan bo'lsa belgilangan bo'ladi.", verbose_name='O‘qilganlik holati'),
        ),
        migrations.AlterField(
            model_name='ogohlantirish',
            name='sarlavha',
            field=models.CharField(help_text="Xabarning qisqa sarlavhasi (masalan: Yangi baho qo'yildi).", max_length=255, verbose_name='Xabar mavzusi'),
        ),
        migrations.AlterField(
            model_name='ogohlantirish',
            name='turi',
            field=models.CharField(choices=[('baho', '📊 Baho haqida ogohlantirish'), ('davomat', '🕒 Davomat (dars qoldirish)'), ('intizom', '⚠️ Intizomiy ogohlantirish'), ('umumiy', '📢 Umumiy e’lon yoki xabar')], default='umumiy', max_length=20, verbose_name='Xabar turi (toifasi)'),
        ),
        migrations.AlterField(
            model_name='ogohlantirish',
            name='yaratilgan_vaqt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana va vaqt'),
        ),
        migrations.AlterModelTable(
            name='ogohlantirish',
            table='tizim_ogohlantirishlari',
        ),
    ]
